name: ingredients
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  flutter_swiper: ^1.1.6
  #  flutter_svg: ^0.17.3
  #  provide: ^1.0.2
  #  url_launcher: ^4.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.1
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.19.1
  provide: ^1.0.2
  url_launcher: ^5.7.8
  http: ^0.12.0+2
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  date_format: ^1.0.9
#  dio: ^2.1.0
  dio: ^3.0.10
  logger: ^0.9.4
    #web
  webview_flutter: ^1.0.7
    #数据库
  sqflite: ^1.3.2+1
    #路径操作
  path: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/lunBoTu/cao_mei.jpg
    - lib/assets/images/lunBoTu/hu_luo_bo.jpg
    - lib/assets/images/lunBoTu/ping_guo.jpg
    - lib/assets/images/lunBoTu/qie_zi.jpg
    - lib/assets/images/lunBoTu/xi_hong_shi.jpg
    - lib/assets/images/lunBoTu/xi_lan_hua.jpg
    - lib/assets/images/lunBoTu/xiang_gu.jpg
    - lib/assets/images/lunBoTu/yang_cong.jpg
    - lib/assets/images/lunBoTu/yu.jpg
    - lib/assets/images/lunBoTu/yu_mi.jpg
    - lib/assets/images/menuImg/cao_mei_jiang.jpg
    - lib/assets/images/menuImg/cao_mei_shan_yao_ni.jpg
    - lib/assets/images/login/my_icon.png
    - lib/assets/images/login/p_loginbg.jpg
    - lib/assets/images/login/p_zhucebg2.jpg
    - lib/assets/images/login/p_zhucebg3.jpg
    - lib/assets/images/loading/openapp.jpg
    - lib/assets/images/login/touxiang.jpg
    - lib/assets/images/loading/loading.jpg
    - lib/assets/images/login/logo.png

      # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

  fonts:
    - family: BQ
      fonts:
        - asset: lib/assets/fonts/ttf/biao_qing.ttf
    - family: iconFont
      fonts:
        - asset: lib/assets/fonts/iconFonts/IconFont.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
